
# Use httpYac - Rest Client extension in Visual Studio Code to run this file in Visual Studio Code


### use this to safe the token in the global variable
POST http://localhost:8080/admin/account/login
Content-Type: application/json

{
    "username": "my_username",
    "password": "my_password"
}
> {%
client.global.set("adminToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsInJvbGVzIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjTGVhcm5lciJdLCJleHAiOjE3NTI4NjE0MDAsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20ifQ.9jggrAL4joVHigURrjbBPrwfV3cBYq6jpg-OUhGxzb0");
client.global.set("instructorToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsInJvbGVzIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjSW5zdHJ1Y3RvciJdLCJleHAiOjE3NTI4NjE0MDAsImVtYWlsIjoiaW5zdHJ1Y3RvcjNAZXhhbXBsZS5jb20ifQ.TE9DBHiggewv16voMXhJ9q5TApvPzOGdZAZbFvIziko");
client.global.set("learnerToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsInJvbGVzIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjTGVhcm5lciJdLCJleHAiOjE3NTI4NjE0MDAsImVtYWlsIjoidXNlcl90ZXN0X2NvbnNpc3RlbnRfMTJ3X2Q4MzgyMTBlQGV4YW1wbGUuY29tIn0.Xd1pefZ1JHypwT3Be5QXHPhK2Q_9wSnLbhbRlQ201nU");
console.log("Hallo")
%}


GET http://localhost:8000/activeUser/30
Authorization: Bearer {{adminToken}}


GET http://localhost:8000/totalCourses
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/totalActivities
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/totalUsers
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/assessmentPerformance?activityId=http://example.com/activities/Test:_Kettensäge_bedienen
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/assessmentPerformance?activityId=http://example.com/activities/Test:_Kettensäge_bedienen
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/popularTimes/18
Authorization: Bearer {{adminToken}}
