
# Use httpYac - Rest Client extension in Visual Studio Code to run this file in Visual Studio Code


### use this to safe the token in the global variable
POST http://localhost:8080/admin/account/login
Content-Type: application/json

{
    "username": "my_username",
    "password": "my_password"
}
> {%
client.global.set("adminToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsInJvbGVzIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjQWRtaW5pc3RyYXRvciJdLCJleHAiOjE3NTMzMTI4MDgsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20ifQ.18JYAn-C-_q3AVNQmir_HksoKul6E1HmHzNd4GxWZRc");
client.global.set("instructorToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsInJvbGVzIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjSW5zdHJ1Y3RvciJdLCJleHAiOjE3NTI4NjE0MDAsImVtYWlsIjoiaW5zdHJ1Y3RvcjNAZXhhbXBsZS5jb20ifQ.TE9DBHiggewv16voMXhJ9q5TApvPzOGdZAZbFvIziko");
client.global.set("learnerToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsInJvbGVzIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjTGVhcm5lciJdLCJleHAiOjE3NTMzNjU1ODIsImVtYWlsIjoidXNlcl90ZXN0X2NvbnNpc3RlbnRfMTJ3XzcyNWJhYzVjQGV4YW1wbGUuY29tIn0.4_gyhiigwSrr87URlUUtN6mIPp7Ced30B5XlJ_OtPr8");
console.log("Hallo")
%}


GET http://localhost:8000/activeUser/30
Authorization: Bearer {{adminToken}}


GET http://localhost:8000/totalCourses
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/totalActivities
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/totalUsers
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/assessmentPerformance
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/popularTimes
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/activityRatings/instructor
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/activityRatings/learner
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/timeSpentOnActivities
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/activityRevisits
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/assessmentAveragesofCourses
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/courseCompletionRate
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/activeUserSubcours/30/instructor
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/activeUserSubcours/30/admin
Authorization: Bearer {{adminToken}}

GET http://localhost:8000/dailyAverageScoreofTheWeek
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/assessmentAttempts
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/attemptsUntilPassed
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/activityEngagement
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/passRate/instructor
Authorization: Bearer {{instructorToken}}

GET http://localhost:8000/passRate/learner
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/learningEffectiveness
Authorization: Bearer {{learnerToken}}

GET http://localhost:8000/activeHoursThisWeek
Authorization: Bearer {{learnerToken}}